# Basic Math Concept 

## We will cover the following main topics in this order

* Python Numberical Types
* Basic Mathmatical Function
* Numpy Array
* Matrices

## Python Numerical Types

Python provides basic numerical types such as arbitrarily sized integers and floating-point number as standard, but it also provides sserval additional types that are useful in specific applications where precision is especially important. Python also provides build-in support for complex numbers, which are useful for some more advanced mathematical application.

### Decimal Types

For application that require decimal digits which accurate arithmatic operation, use the decimal type form the decimal module in the python standard Library

In [1]:
from decimal import Decimal 
num1 = Decimal('1.1')
num2 = Decimal('1.563')
num1 + num2 

Decimal('2.663')

The decimal type is based on the IBM General Decimal Arithmetic Specification which is an alternative specification for floating-point arithmatic that represents decimal numbers exactly by using powrs of 10 rather that power of 2. This mean that it can be safely used for calculations in finance where the accumulation of rounding error would have dire consequences. However, the decimal format is less memory efficient, since it must store decimal digits rather than binary digits, and are more computationally expensive that traditional floating-point number.

### Fraction Type 

Alternatively, for working with applications that require accurate representations of integer fraction, such as when working with porportions or probabilities, there is the Fraction type from the fractions module in the python standard library. The usage is similar, except that we typically give the numerator and denominator of the fraction as arguments:

In [4]:
from fractions import Fraction
num1 = Fraction(1, 3)
num2 = Fraction(4, 7)
num1 * num2 

Fraction(4, 21)

From the fraction above, 4 is the numerator and 21 is the denominator, so if you want to get the numerator or denominator from this fraction you can use:

In [5]:
result= num1*num2
numerator = result.numerator
denominator = result.denominator


In [6]:
numerator 

4

In [7]:
denominator 

21

### Complex Type 

Python also has support for complex number, including a literal charater to denote the complex unit 1j in code. This might be different from the idiom for representing the complex until that you are familiar with from other sources on complex number. Most mathmatical texts will often use the symbol i to represent the complext unit:

In [11]:
z = 1 + 1j
z + 2+ 3j

(3+4j)

In [12]:
z.conjugate()

(1-1j)

conjugate means to change the sign of the imaginary part, z = 1+1j, conjugate change from 1j to -1j

## Basic Mathematical Functions

Basic mathematical function appear in many applications. For example, logarithms can be used to scal data that grows exponentially to give linear data. The exponential function and trigonometric functions are common fixtures when working with geometric information, the gamma function appears in combinatorics, and the Gaussian error function is important in statistic.

The math module in the python standard library provides all of the standard mathematical functions, along with common constants and some utility functions, and it can be imported using the following command.


In [14]:
import math 

For instance, to find the square root of a non-negative number, we would use the sqrt function from math

In [15]:
import math 
math.sqrt(4)

2.0

The trigonometric function, sine, cosine, and tanget, are available under their common abbreviations sin, cos, and tan, respectively, in the math module. The pi constant hold the value of $\pi$ which is approximately 3.1416

In [29]:
theta = math.pi/4*(180/math.pi)
math.cos(theta)

0.5253219888177297

To convert an angle from radians to degrees, you can use the formula:
\begin{equation}
    degree = radian\times \frac{180}{\pi}
\end{equation}

## Numpy Arrays 

Numpy Array provides high performance array types and routines for manipulating these arrays in python. These arrays are useful for processing large datasets where performance is crucial. Numpy froms the base fro the numerical and scientific computing stack in Python. Under the hood, Numpy make use of low-level libraries for working with vectors and matrics, such as the *Basic linear Algebra Subprogram and the Linear Algegra Package contain more advanced routines for linear algebra

Traditoinally, the numpy package is import under the shorter alias np, which can be accomplished using the following import statement`

In [30]:
import numpy as np

For example, we can create a simple array by providing a list with the required element 

In [31]:
arr = np.array([1,2,3,4])

In [32]:
arr

array([1, 2, 3, 4])

Numpy will infer an appropriate data type during creation if one is not explicitly provided using the dtype keyword argument:

In [34]:
arr1 = np.array([1,2,3,4], dtype= np.float32)

In [35]:
arr1

array([1., 2., 3., 4.], dtype=float32)

In [36]:
arr = np.array([1.4,2,3,4])

In [37]:
arr

array([1.4, 2. , 3. , 4. ])

instead if you wish to change the data type after creation, use the astype method to specify the new type. The correct way to change the data type is shown here

In [38]:
arr = arr.astype(np.float32)

In [40]:
print(arr)

[1.4 2.  3.  4. ]


## Element Access 

Numpy array support the getitem protocol, so elements in an array can accessed as if it were a list and support all of the arithmetic operation, which are performed componentwise. This mean that we can use the index notation and the index to retrieve the element from the specified index ads follows

In [41]:
arr = np.array([1,2,3,4])

In [42]:
arr[0]

1

In [43]:
arr[3]

4

This also includes the usual slice syntax for extracting an array of data from an existing array. A slice of an array is again an array, containing the elements specified by the slice. For example, we can retrieve an array containing the first two element of arr, or an array as follow:

In [44]:
first_two = arr[:2]

In [45]:
first_two

array([1, 2])

In [46]:
even_idx = arr[::2]

In [47]:
even_idx 

array([1, 3])

In [50]:
last_two = arr[-2:]

In [51]:
last_two

array([3, 4])

## Using array creation Routines

To generate arrays of numbers at regula interval between two given end points, you can use either the arange routine or the linspace routine. The difference between thes two routines is that linespace generate a number (the default is 50) of values with equal spacing between the two end points, including both end points, while arange generates numbers at a given step size up to, but not including the upper limit. The linespace routine generates values in the closed interval $a\leq{x}\leq{b}$ and the arrange generates values in the half-open interval $a\leq{x}<{b}$

In [52]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [54]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])